name: homelab-hass
services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    # env_file:
    #   - /opt/homelab/.env
    environment:
      - TZ=${TZ}
    volumes:
      - /opt/homelab/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /dev/serial/by-id:/dev/serial/by-id
      - /srv/media:/media
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
      - /dev/ttyS4:/dev/ttyS4
      - /dev/ttyACM0:/dev/ttyACM0
    restart: unless-stopped
    privileged: true
    network_mode: host
    depends_on:
      - influxdb
      - mariadb
      - matter-server

  hass-configurator:
    container_name: hassconf
    image: causticlab/hass-configurator-docker
    depends_on:
      - homeassistant
    volumes:
      - /opt/homelab/homeassistant/hassconf:/config
      - /opt/homelab/homeassistant/config:/hass-config
    ports:
      - "3218:3218"
    restart: unless-stopped

  matter-server:
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    container_name: matter-server
    restart: unless-stopped
    # Required for mDNS to work correctly
    network_mode: host
    environment:
      MATTER_NETWORK_INTERFACE: wlxf0a731ceb4d1
    security_opt:
      # Needed for Bluetooth via dbus
      - apparmor:unconfined
    volumes:
      # Create an .env file that sets the USERDIR environment variable.
      - /opt/homelab/homeassistant/matter-server/data/:/data/
      # Required for Bluetooth via D-Bus
      - /run/dbus:/run/dbus:ro
    # If you adjust command line, make sure to pass the default CMD arguments too:
    #command: --storage-path /data --paa-root-cert-dir /data/credentials --bluetooth-adapter 0
