name: homelab-media
services:
    jellyfin:
        image: jellyfin/jellyfin:12.0.20260908-012347
        # labels:
        #   tsdproxy.enable: "true"
        #   tsdproxy.name: "jellyfin"
        #   tsdproxy.container_port: "8096"
        container_name: jellyfin
        volumes:
            - /opt/homelab/media/jellyfin/config:/config
            - /opt/homelab/media/jellyfin/cache:/cache
            - type: bind
              source: /mnt/ext_x10p/media
              target: /media
            - type: bind
              source: /mnt/ext_x9/media
              target: /media_x9
            - type: bind
              source: /mnt/nvme1/media
              target: /media_nvme1
            - type: bind
              source: /mnt/nvme2/media
              target: /media_nvme2
        devices:
            - /dev/dri/renderD128:/dev/dri/renderD128
        group_add:
            - "991" # render group on host, grants access to /dev/dri
        ports:
            - "8096:8096"
        restart: unless-stopped
        networks:
            - default

    filebrowser:
        image: gtstef/filebrowser:1.5.8-stable
        container_name: filebrowser
        ports:
            - 8900:80
        restart: unless-stopped
        user: "${PUID}:${PGID}"
        volumes:
            - /opt/homelab/media/filebrowser:/home/filebrowser/data
            - /mnt/ext_x10p:/srv/x10p
            - /mnt/ext_x9:/srv/x9
            - /mnt/nvme1:/srv/nvme1
            - /mnt/nvme2:/srv/nvme2
    navidrome:
        image: deluan/navidrome:0.63.2
        container_name: navidrome
        user: "${PUID}:${PGID}"
        environment:
            - ND_SCANSCHEDULE=1h
            - ND_LOGLEVEL=info
            - ND_LISTENBRAINZ_BASEURL=http://maloja:42010/apis/listenbrainz/1/
            - TZ=Europe/Amsterdam
        volumes:
            - /opt/homelab/media/navidrome/data:/data
            - /mnt/ext_x10p/media/music:/music
            - /mnt/nvme1/media/music:/music_nvme1
            - /mnt/nvme2/media/music:/music_nvme2
        ports:
            - "4533:4533"
        restart: unless-stopped

    maloja:
        image: krateng/maloja:3.2.6
        container_name: maloja
        environment:
            - MALOJA_DATA_DIRECTORY=/data
            - TZ=Europe/Amsterdam
        volumes:
            - /opt/homelab/media/maloja/data:/data
        ports:
            - "42010:42010"
        restart: unless-stopped

    komga:
        image: gotson/komga:1.26.3
        container_name: komga
        volumes:
            - /opt/homelab/media/komga:/config
            - /mnt/nvme2/comics:/data/comics
            - /mnt/ext_x10p/media/books:/data/books
        ports:
            - 25600:25600
        user: "${PUID}:${PGID}"
        environment:
            - TZ=Europe/Amsterdam
            - JAVA_TOOL_OPTIONS=-Xmx1g
        restart: unless-stopped
